name: Preview DNS Changes

on:
  pull_request:

jobs:
  deploy:
    name: Run DNS Control
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            **Hello**
            🌏
            !
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::171269869827:role/GitHubMattCantyDNSActionsWrite
          aws-region: eu-west-2
      - name: Git clone the repository
        uses: actions/checkout@v2
      - name: DNSControl check
        uses: koenrh/dnscontrol-action@v3
        with:
          args: check
      - name: DNSControl preview
        id: dnscontrol_preview
        uses: koenrh/dnscontrol-action@v3
        with:
          args: preview
