name: Run DNS Control

on:
  push:
    ignore_branches:
      - main

jobs:
  deploy:
    name: Run DNS Control
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::171269869827:role/GitHubMattCantyDNSActionsWrite
          aws-region: eu-west-2
      - name: Git clone the repository
        uses: actions/checkout@v2
      - name: DNSControl check
        uses: koenrh/dnscontrol-action@v3
        with:
          args: check
      - name: DNSControl preview
        id: dnscontrol_preview
        uses: koenrh/dnscontrol-action@v3
        with:
          args: preview
      - name: Preview pull request comment
        uses: unsplash/comment-on-pr@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            ```
            ${{ steps.dnscontrol_preview.outputs.preview_comment }}
            ```
          check_for_duplicate_msg: true