name: Deploy OIDC CloudFormation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Run DNS Control
    runs-on: stackexchange/dnscontrol
# arn:aws:iam::171269869827:role/GitHubMattCantyDNSActionsWrite