name: Run DNS Control

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Run DNS Control
    runs-on: stackexchange/dnscontrol
    steps:
      - name: Checkout
        uses: actions/checkout@v2
# arn:aws:iam::171269869827:role/GitHubMattCantyDNSActionsWrite